package service;

import model.LessonPlan;
import util.ErrorLogger;

import com.lowagie.text.Document;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.pdf.PdfWriter;

import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Service for exporting lesson plans to PDF and Word formats.
 */
public class ExportService {
    
    private static ExportService instance;
    private ErrorLogger errorLogger;
    
    private ExportService() {
        errorLogger = ErrorLogger.getInstance();
    }
    
    public static synchronized ExportService getInstance() {
        if (instance == null) {
            instance = new ExportService();
        }
        return instance;
    }
    
    /**
     * Export a lesson plan to PDF format.
     * 
     * @param lessonPlan The lesson plan to export
     * @param outputPath The file path where the PDF should be saved
     * @return true if export was successful, false otherwise
     */
    public boolean exportToPDF(LessonPlan lessonPlan, String outputPath) {
        try {
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream(outputPath));
            
            document.open();
            
            // Title
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Font.BOLD);
            Paragraph title = new Paragraph("Lesson Plan: " + lessonPlan.getTitle(), titleFont);
            title.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(title);
            
            document.add(new Paragraph(" ")); // spacer
            
            // Metadata
            Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12);
            Font boldFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12);
            
            document.add(new Paragraph("Subject: ", boldFont));
            document.add(new Paragraph(lessonPlan.getSubject(), normalFont));
            document.add(new Paragraph("Grade: ", boldFont));
            document.add(new Paragraph(lessonPlan.getGradeLevel(), normalFont));
            document.add(new Paragraph("Term: ", boldFont));
            document.add(new Paragraph(lessonPlan.getTerm(), normalFont));
            document.add(new Paragraph("Topic: ", boldFont));
            document.add(new Paragraph(lessonPlan.getTopic(), normalFont));
            document.add(new Paragraph("Duration: ", boldFont));
            document.add(new Paragraph(lessonPlan.getDurationMinutes() + " minutes", normalFont));
            document.add(new Paragraph("Scheduled Date: ", boldFont));
            document.add(new Paragraph(lessonPlan.getLessonDate(), normalFont));
            document.add(new Paragraph("Status: ", boldFont));
            document.add(new Paragraph(lessonPlan.getStatus(), normalFont));
            
            document.add(new Paragraph(" ")); // spacer
            document.add(new Paragraph(" ")); // spacer
            
            // Learning Objectives
            document.add(new Paragraph("Learning Objectives:", boldFont));
            document.add(new Paragraph(lessonPlan.getObjectives(), normalFont));
            
            document.add(new Paragraph(" ")); // spacer
            
            // Teaching Activities
            document.add(new Paragraph("Teaching Activities:", boldFont));
            document.add(new Paragraph(lessonPlan.getTeachingActivities(), normalFont));
            
            document.add(new Paragraph(" ")); // spacer
            
            // Assessment Method
            document.add(new Paragraph("Assessment Method:", boldFont));
            document.add(new Paragraph(lessonPlan.getAssessmentMethod(), normalFont));
            
            document.add(new Paragraph(" ")); // spacer
            
            // Resources
            document.add(new Paragraph("Resources:", boldFont));
            document.add(new Paragraph(lessonPlan.getResources(), normalFont));
            
            document.add(new Paragraph(" ")); // spacer
            document.add(new Paragraph(" ")); // spacer
            
            // Footer
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA, 9);
            Paragraph footer = new Paragraph(
                "Generated by Digital Lesson Planner on " + 
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")),
                footerFont
            );
            footer.setAlignment(Paragraph.ALIGN_CENTER);
            document.add(footer);
            
            document.close();
            
            errorLogger.logInfo("ExportService", "exportToPDF", "Exported lesson plan " + lessonPlan.getLessonPlanId() + " to PDF: " + outputPath);
            return true;
            
        } catch (Exception e) {
            errorLogger.logError("ExportService", "exportToPDF", "Failed to export lesson plan to PDF: " + e.getMessage(), e);
            return false;
        }
    }
    
    /**
     * Export a lesson plan to Word (DOCX) format.
     * 
     * @param lessonPlan The lesson plan to export
     * @param outputPath The file path where the DOCX should be saved
     * @return true if export was successful, false otherwise
     */
    public boolean exportToWord(LessonPlan lessonPlan, String outputPath) {
        try (XWPFDocument document = new XWPFDocument()) {
            
            // Title
            XWPFParagraph title = document.createParagraph();
            title.setAlignment(org.apache.poi.xwpf.usermodel.ParagraphAlignment.CENTER);
            XWPFRun titleRun = title.createRun();
            titleRun.setText("Lesson Plan: " + lessonPlan.getTitle());
            titleRun.setBold(true);
            titleRun.setFontSize(18);
            titleRun.setFontFamily("Calibri");
            
            // Metadata section
            addMetadataField(document, "Subject", lessonPlan.getSubject());
            addMetadataField(document, "Grade", lessonPlan.getGradeLevel());
            addMetadataField(document, "Term", lessonPlan.getTerm());
            addMetadataField(document, "Topic", lessonPlan.getTopic());
            addMetadataField(document, "Duration", lessonPlan.getDurationMinutes() + " minutes");
            addMetadataField(document, "Scheduled Date", lessonPlan.getLessonDate());
            addMetadataField(document, "Status", lessonPlan.getStatus());
            
            // Learning Objectives
            addSectionHeading(document, "Learning Objectives");
            addParagraph(document, lessonPlan.getObjectives());
            
            // Teaching Activities
            addSectionHeading(document, "Teaching Activities");
            addParagraph(document, lessonPlan.getTeachingActivities());
            
            // Assessment Method
            addSectionHeading(document, "Assessment Method");
            addParagraph(document, lessonPlan.getAssessmentMethod());
            
            // Resources
            addSectionHeading(document, "Resources");
            addParagraph(document, lessonPlan.getResources());
            
            // Footer
            XWPFParagraph footer = document.createParagraph();
            footer.setAlignment(org.apache.poi.xwpf.usermodel.ParagraphAlignment.CENTER);
            XWPFRun footerRun = footer.createRun();
            footerRun.setText("Generated by Digital Lesson Planner on " + 
                LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm")));
            footerRun.setFontSize(9);
            footerRun.setItalic(true);
            
            // Save document
            try (FileOutputStream out = new FileOutputStream(outputPath)) {
                document.write(out);
            }
            
            errorLogger.logInfo("ExportService", "exportToWord", "Exported lesson plan " + lessonPlan.getLessonPlanId() + " to Word: " + outputPath);
            return true;
            
        } catch (IOException e) {
            errorLogger.logError("ExportService", "exportToWord", "Failed to export lesson plan to Word: " + e.getMessage(), e);
            return false;
        }
    }
    
    private void addMetadataField(XWPFDocument document, String label, String value) {
        XWPFParagraph p = document.createParagraph();
        XWPFRun labelRun = p.createRun();
        labelRun.setText(label + ": ");
        labelRun.setBold(true);
        XWPFRun valueRun = p.createRun();
        valueRun.setText(value);
    }
    
    private void addSectionHeading(XWPFDocument document, String heading) {
        XWPFParagraph p = document.createParagraph();
        XWPFRun run = p.createRun();
        run.setText(heading);
        run.setBold(true);
        run.setFontSize(14);
        
        // Add spacing after heading
        XWPFParagraph spacer = document.createParagraph();
        spacer.setSpacingAfter(200);
    }
    
    private void addParagraph(XWPFDocument document, String text) {
        XWPFParagraph p = document.createParagraph();
        XWPFRun run = p.createRun();
        run.setText(text);
        p.setSpacingAfter(200);
    }
}